services:
  dog-nose-ai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dog-nose-ai-service
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models:ro  # 모델 파일을 읽기 전용으로 마운트
      - ./logs:/app/logs         # 로그 디렉토리
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
      - CUDA_VISIBLE_DEVICES=0   # GPU 사용 설정 (필요한 경우)
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]  # GPU 지원 (nvidia-docker 필요)

  # Redis (선택사항 - 캐싱용)
  redis:
    image: redis:7-alpine
    container_name: dog-nose-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru

networks:
  default:
    name: dog-nose-network 